### ISSUE TITLE
To add to the repo/inventory

### ISSUE THREAD

**Issue by Erioldoesdesign** [sustainers/design#10]
https://wiki.documentfoundation.org/Design/Principles

**Comment by jwflory** [comment]
Looks like a good addition. Do you think it belongs in Case Studies & Examples section? Maybe we could add a reading list page to that section to start curating this type of content.

**Comment by Erioldoesdesign** [comment]
> Looks like a good addition. Do you think it belongs in Case Studies & Examples section? Maybe we could add a reading list page to that section to start curating this type of content.

I think Case Studies and Examples is a good section for this 😄 and a reading list page sounds fantastic. I'll look at describing some issues and raising some PR's this weekend

**Comment by jwflory** [comment]
@Erioldoesdesign If it helps, I can create the reading list to kick things off. Or if you'd prefer to try your hand at this, happy to hold off. Let me know your preference!

**Comment by Erioldoesdesign** [comment]
> @Erioldoesdesign If it helps, I can create the reading list to kick things off. Or if you'd prefer to try your hand at this, happy to hold off. Let me know your preference!

That would be very helpful and lovely! thank you 🙏

**Comment by jwflory** [comment]
@Erioldoesdesign Done in PR #11! Ready for you and the team's review. 🌟
