### ISSUE TITLE
Add the SOSD Spotlights to the website

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/design#14]
We have a list of resources and people that are awesome, drawn from the SOSD Podcast! https://docs.google.com/document/d/1JtSY389IChP_fvylXJv4OgHJVM8A4O4XC6g9QCwXJfo/edit

It would be great to add these to the website. They should go here: https://sustainers.github.io/design/examples/

Would someone be able to help with this?

**Comment by jwflory** [comment]
In the GitHub repo, this would look like a new file, maybe a "Hall of Fame" or "Projects" page, found here:

**Comment by m5kr1pka** [comment]
@Erioldoesdesign  is there any direction design wise for this content?

**Comment by m5kr1pka** [comment]
@RichardLitt do you want to pull only people from that document or all material? And do you think better would be to add a link in sidebar to that page, or update the index with big banner to podcast Hall of fame?

**Comment by RichardLitt** [comment]
Ah, I like that idea!
