### ISSUE TITLE
New page: Invitation text for SOS Design podcast

### ISSUE THREAD

**Issue by jwflory** [sustainers/design#16]
# Summary

Create a new page with the invitation test for the SOS Design podcast

# Background

In the 14 March 2022 meeting, it came up if there was an invitation template we could use for inviting people to the podcast. This would make it easier for us to share invites for people asynchronously. We can personalize the template for whoever we are inviting.

# Details

@RichardLitt had a clear idea of what this would look like, and volunteered to draft it. Perhaps we could create a "Meta" or "Podcast" category to group documentation and notes about our working group itself. Or if not, maybe just the podcast.

# Outcome

Simplify inviting others to the podcast and improve consistency in messaging around the podcast

**Comment by RichardLitt** [comment]
I believe this is done. I don't want the page to be public, but I've shared with all of the podcasts hosts for now. Good call, @jwf! 

This can't be personalized, but it will help.

**Comment by jwflory** [comment]
@RichardLitt Would it make sense to create a new category for the podcast on this site? It could also be a "hidden" category that does not appear on the home page.

**Comment by RichardLitt** [comment]
I don't understand.

**Comment by Erioldoesdesign** [comment]
Yeah I'm not sure what is mean't by a new category - is that the main 'squares' on the homepage?

I think what's being suggested by Justin is possibly, creating a new 'category' for the podcast intro text on a hidden page on the design inventory that we can then link out to guests? but that's my guess.

**Comment by RichardLitt** [comment]
> I think what's being suggested by Justin is possibly, creating a new 'category' for the podcast intro text on a hidden page on the design inventory that we can then link out to guests? but that's my guess.

If so, I'm curious what the current page doesn't offer? See https://sosdesign.sustainoss.org/invite.

**Comment by Erioldoesdesign** [comment]
oh it offers all it needs to, but it's not hosted on the inventory page right? it's on the sustain site?

**Comment by RichardLitt** [comment]
Yeah. It's on the podcast platform. I don't think it needs to be on the inventory page.

**Comment by jwflory** [comment]
> **_@Erioldoesdesign wrote…_**
> Yeah I'm not sure what is mean't by a new category - is that the main 'squares' on the homepage?
> 
> I think what's being suggested by Justin is possibly, creating a new 'category' for the podcast intro text on a hidden page on the design inventory that we can then link out to guests? but that's my guess.

Yes, this is right. A new category for meta documentation about how we run the show, our process, a notes template, etc. We don't have to do it, but it is useful information we should probably capture somewhere outside of our heads (mostly). Whether that information belongs on this site or not is the question.

> **_@RichardLitt wrote…_**
> If so, I'm curious what the current page doesn't offer? See https://sosdesign.sustainoss.org/invite.
>
> […]
>
> Yeah. It's on the podcast platform. I don't think it needs to be on the inventory page.

It is more natural for this to be on the podcast website. I forgot this page was put up. It meets my needs for facilitating invites to the show. 👍🏻

**Comment by RichardLitt** [comment]
> Whether that information belongs on this site or not is the question.

I think maybe just a GitHub repo would be easier? Not sure this needs to be for other people.
